sudo: required
language: php
php:
- 7.1.9
branches:
  only:
  - master
env:
  global:
  - ZIP_FILE="php-$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT.zip"
  - secure: ''
  - secure: ''
  - secure: ''
  - secure: ''
  - secure: "MSzkZ2/N9HVeQG3LIDa2PRBG4nDjdhNVXc5L2MDmB2+A3KcqH5w7txekQ1sGgBTwd4SAUvFcqqq2L49pC53bNeZFggGUC2JOBq3p6A8cSniwlr1fwTex9epi4s/i03Eu9HZbWOKA5Sesw3XT2fLmUtVxhDkIsOcg9wd8MsHOiJZH7rR9FkPrTF3mx+3+3X/3FIFZ38lUWLUlN/z8Taa4w/kV6Ig1XT2Or0lsP8dlogiZL5hz/snsrEBOq4EFXegXusINuuJe5N1/XTJIzO+KvPu2V78Nq+jWMXdFpAfWHuanMWvxRsAvMDwRc1zbQm9AakIl6Kzp5Roe1inILOMD+4SwdYc8YMYV0CT4473Nb5Bk+g49xgCyeKNff5WUUHEtCHRYZzMaY48xpXXzcwQHEDP/BTl9EH8a+2i0ZET1JlLr5PjSBbD1TqWPiTuvCX2/zaYm80amLurOD5pTcMAAd8rc614siLZhs0oePzPAIEm3Pl4nWqUsSvwZ70SZQ0C57L1Pd2Id4W7y7SZWlR4UKK/YWXWZgFXsLDbwEQ1NSjVYUtnr4dd3cznD0PiZCWMSxhRBRDyF943C0V8iWv27SoeAyEGUvuB8BG1gliLqaqPmnsxs8v8neVrl9GiESNbutVZzUC7rJB+8nRddr2Fzc8X6ZTAcz132jHaSpCjoAqs="
  - secure: "T9Tb9QA4EeswUP7DO9y+U7xAEWDCBh6MIn8RlGXM19Lld6F7OSAwmI2B/wJS7FUyV2GqyiMSSPwnIBqgWaRCX4KuRfULCwfmcbNFMPq3zewTuHicp3R5YibIPoSZ1HxxuwG3wIAcnKJUXmWzkbUXkydLs/pUJ21FOHk6jTkFknLcYLua+2jnC/xMXwp0cxJrrrlhV1rQ5hSvtLhRK7hzXyO5omDBuFJf5gN9IZuu/Inb96rPUhuV66dqlzHRq4bKTd6rvHaZrUhJxMMQ8kHCFHKzoNchqYCFAKcEIyJHswjxQj2bPSKg6cIqBPVjHG1XMnXXPf7w2R2YPXo259EoYg0bPhBl+Nd7yFbSrgGWNzgTzWbUa1hKEjrPsAwm/IqV79SVhdwIu5iS3jbA3CvMRR9TJ+nHGkExxl19UE4p4k8mxDALZRz9E0CPaKXETIKMp+/Y/kpgzCgrKQ6y5vsYzQQ9SYEmSxgUCKzC7yV2bPwmb99qN4PXAf936Hh48KwU6dE2d1rUfaRydXk5UhcK2MCMHug5vIqG/Nw5c6iHdIdcs+Q0okCd9avRbk5iyIpy4AG6Fc+OG38pX1eJgL8FCkWOCINKgac7FYyWZU/1P3qPfpWaaad4QUAQpBg9h5phLSrFDp84okyWbnggtpP2pnVjaqUaIwjhgVVynMdzwxY="
  - AWS_ACCESS_KEY_ID=''
  - AWS_SECRET_ACCESS_KEY=''
  - AWS_REGION='ap-northeast-1'
  - CODEDEPLOY_APP_NAME=''
  - CODEDEPLOY_GROUP=''
notifications:
  email:
    on_failure: always
    on_success: never
  slack:
    secure: faQHYiO4gqHDRcp1eZoPTS03eulmedP9uhmbsxe4OvN1YZxIfocjGV7hQi/Q3uqsTsMgnOcGvyw4Od+ypvxYCzyfD55ox2hVqAK0ypEKWqHz7jkTZU3s7ieUwhVwkpaJUV4dfy5TVBdTgb1PE6IlbrdYTRsxDjZ4dto75oDZF/UAVV5TbJQVdSDHCZ0y8Pkz0ZgkMbxPH/k4swienqKhZhFcqlGoeA0X/MottUXqeYs3+wClfyyfpMnLGozmfjOZYUj4NH6wzzS56IqilSQDBx41ILx/JgqfZAqr/edSg3UxtAduMYNwqJ8g8RPgCDFuDEKbu16crcqwEcNmFfV0ijLXdk+o5ZNt92dcuabEcxZuM6p4rN1zl0ngJBy1cTXluEwLiBadjyA+NKo8ds1ZN7t/WfKtPUtYtzeFLz8ovFIMC654l4Fts4u8LkY+TmfzwHgCWtl+lO/V3BdYW5rZhzbbmJa2qyfJtGpVt6Q+3Emza1ROjDHwa7+zpOMoxTWHh7AC//uNS4REIJUx6qFMbl+mKtedlqpNm2Ct5nxAg5sKpyExp4XrornjmvFUUpLY9iJ2ySwGb7S5Rj+kmEdQl29p0O4dc1PEDDM0XImI6rutQw4OL6GehsS0r30DSLXp0gIbbxDibiqKtDGddSOKSG9PCgAmTxCP6mhn9uB4CBI=
cache:
  directories:
  - "$COMPOSER_CACHE_DIR"
  - "$HOME/.composer/cache"
before_install:
- set -e
- echo `date +"%Y-%m-%d %H:%M:%S"`
- echo $TRAVIS_BRANCH
- if [[ $TRAVIS_BRANCH == "dev" ]]; then AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV;
  AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV; S3_BUCKET=''; CODEDEPLOY_APP='';
  CODEDEPLOY_GROUP=''; fi
- if [[ $TRAVIS_BRANCH == "staging" ]]; then AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STG;
  AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STG; S3_BUCKET=''; CODEDEPLOY_APP='';
  CODEDEPLOY_GROUP=''; fi
- if [[ $TRAVIS_BRANCH == "master" ]]; then AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD;
  AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD; S3_BUCKET='aws-learning-adsfhojkncxvijoasdf104';
  CODEDEPLOY_APP='aws-learning-Tai-20200117-EC2-CodeDeploy'; CODEDEPLOY_GROUP='ec2'; fi
script:
- echo 'script step...'
before_deploy:
- cd "$TRAVIS_BUILD_DIR"; mkdir "$TRAVIS_BUILD_DIR/zip"; zip -r "$TRAVIS_BUILD_DIR/zip/$ZIP_FILE"
  *
deploy:
- provider: S3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "$AWS_REGION"
  local_dir: "$TRAVIS_BUILD_DIR/zip"
  bucket: "$S3_BUCKET"
  skip_cleanup: true
  on:
    all_branches: true
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "$AWS_REGION"
  bucket: "$S3_BUCKET"
  key: "$ZIP_FILE"
  bundle_type: zip
  application: "$CODEDEPLOY_APP"
  deployment_group: "$CODEDEPLOY_GROUP"
  wait_until_deployed: true
  on:
    all_branches: true
